# Generated by Django 2.0.2 on 2018-02-13 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space', models.CharField(choices=[('B@Labs - Av. Habib Bourguiba', 'B@Labs - Av. Habib Bourguiba')], default='B@Labs - Av. Habib Bourguiba', max_length=100)),
                ('typeOf', models.CharField(choices=[('Small meeting room', 'Small meeting room'), ('Medium meeting room', 'Medium meeting room'), ('Big meeting room', 'Big meeting room')], default='Small meeting room', max_length=100)),
                ('date', models.DateField(null=True)),
                ('startTime', models.TimeField(blank=True, null=True)),
                ('duration', models.CharField(choices=[('30', '30'), ('60', '60')], default='30', max_length=100)),
                ('extraTime', models.CharField(choices=[('0', '0'), ('2h', '2h'), ('3h', '3h')], default='2hr', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup', models.CharField(max_length=50)),
                ('profilePic', models.ImageField(null=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.UserInfo'),
        ),
    ]
