# Generated by Django 2.0.2 on 2018-02-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20180213_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='typeOf',
            field=models.CharField(choices=[('Small meeting room', 'Small meeting room'), ('Training Room', 'Training Room'), ('Big meeting room', 'Big meeting room')], default='Small meeting room', max_length=100),
        ),
    ]
