# Generated by Django 2.0.2 on 2018-02-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0005_auto_20180219_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='notes',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
