# Generated by Django 2.0.2 on 2018-02-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0010_auto_20180221_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='product',
            field=models.CharField(choices=[('Kitchen / Coffee', 'Kitchen / Coffee'), ('Cleanness / Hygiene', 'Cleanness / Hygiene'), ('Internet / WIFI', 'Internet / WIFI'), ('Other', 'Other')], default='Kitchen / Coffee', max_length=200),
        ),
    ]
